version: "2.1"

services:
    mobo-db:
        image: mysql:8.0
        volumes:
            - "./shared/db:/var/lib/mysql:Z"
        environment:
            - MYSQL_DATABASE=cms
            - MYSQL_USER=cms
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        mem_limit: 1g
        env_file: config.env
        restart: always
        container_name: MoboCMS-db
    mobo-xmr:
        image: ghcr.io/xibosignage/xibo-xmr:0.11
        ports:
            - "9505:9505"
        restart: always
        mem_limit: 256m
        env_file: config.env
        container_name: MoboCMS-xmr
    mobo-web:
        image: ghcr.io/xibosignage/xibo-cms:release-4.1.2
        volumes:
            - "./shared/cms/custom:/var/www/cms/custom:Z"
            - "./shared/backup:/var/www/backup:Z"
            - "./shared/cms/web/theme/custom:/var/www/cms/web/theme/custom:Z"
            - "./shared/cms/library:/var/www/cms/library:Z"
            - "./shared/cms/web/userscripts:/var/www/cms/web/userscripts:Z"
            - "./shared/cms/ca-certs:/var/www/cms/ca-certs:Z"
        restart: always
        environment:
            - MYSQL_HOST=mobo-db
            - XMR_HOST=mobo-xmr
            - CMS_USE_MEMCACHED=true
            - MEMCACHED_HOST=mobo-memcached
        env_file: config.env
        ports:
            - "80:80"
        mem_limit: 1g
        container_name: MoboCMS-web
    mobo-memcached:
        image: memcached:alpine
        command: memcached -m 15
        restart: always
        mem_limit: 100M
        container_name: MoboCMS-memcached
    mobo-quickchart:
      image: ianw/quickchart
      restart: always
      container_name: MoboCMS-quickchart
