version: "3"

services:
  db:
    image: mysql:8.0
    ports:
    - 3315:3306
    volumes:
    - ./containers/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "cms"
    container_name: MoboCMS-db

  xmr:
    image: ghcr.io/xibosignage/xibo-xmr:latest
    ports:
    - "9505:9505"
    environment:
      XMR_DEBUG: "true"
      IPV6RESPSUPPORT: "false"
      IPV6PUBSUPPORT: "false"
    container_name: MoboCMS-xmr

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
    - ./:/var/www/cms
    ports:
    - "80:80"
    environment:
      CMS_DEV_MODE: "true"
      MYSQL_DATABASE: "cms"
    container_name: MoboCMS-webui

  memcached:
    image: memcached:alpine
    command: memcached -m 15
    container_name: MoboCMS-memcached

  swagger:
    image: swaggerapi/swagger-ui:latest
    ports:
    - "8080:8080"
    environment:
    - API_URL=http://localhost/swagger.json
    container_name: MoboCMS-swagger

  quickchart:
    image: ianw/quickchart
    container_name: MoboCMS-quickchart
