version: "2.1"

services:
    mobo-db:
        image: mysql:8.0
        volumes:
            - "./shared/db:/var/lib/mysql:Z"
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        mem_limit: 1g
        env_file: config.env
        restart: always
        container_name: MoboCMS-db
    mobo-xmr:
        image: ghcr.io/xibosignage/xibo-xmr:0.11
        ports:
            - "9505:9505"
        restart: always
        mem_limit: 256m
        env_file: config.env
        container_name: MoboCMS-xmr
    mobo-web:
        build:
          context: .
          dockerfile: Dockerfile
          args:
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            XMR_HOST: ${XMR_HOST}
            CMS_SERVER_NAME: ${CMS_SERVER_NAME}
            CMS_SMTP_SERVER: ${CMS_SMTP_SERVER}
            CMS_SMTP_USERNAME: ${CMS_SMTP_USERNAME}
            CMS_SMTP_PASSWORD: ${CMS_SMTP_PASSWORD}
            CMS_SMTP_USE_TLS: ${CMS_SMTP_USE_TLS}
            CMS_SMTP_USE_STARTTLS: ${CMS_SMTP_USE_STARTTLS}
            CMS_SMTP_REWRITE_DOMAIN: ${CMS_SMTP_REWRITE_DOMAIN}
            CMS_SMTP_HOSTNAME: ${CMS_SMTP_HOSTNAME}
            CMS_SMTP_FROM_LINE_OVERRIDE: ${CMS_SMTP_FROM_LINE_OVERRIDE}
            CMS_SMTP_FROM: ${CMS_SMTP_FROM}
            CMS_USE_MEMCACHED: ${CMS_USE_MEMCACHED}
            CMS_PHP_POST_MAX_SIZE: ${CMS_PHP_POST_MAX_SIZE}
            CMS_PHP_UPLOAD_MAX_FILESIZE: ${CMS_PHP_UPLOAD_MAX_FILESIZE}
            CMS_PHP_MAX_EXECUTION_TIME: ${CMS_PHP_MAX_EXECUTION_TIME}
            CMS_PHP_SESSION_GC_MAXLIFETIME: ${CMS_PHP_SESSION_GC_MAXLIFETIME}
            CMS_PHP_MEMORY_LIMIT: ${CMS_PHP_MEMORY_LIMIT}
            CMS_QUICK_CHART_URL: ${CMS_QUICK_CHART_URL}
            MEMCACHED_HOST: ${MEMCACHED_HOST}
            GIT_COMMIT: ${GIT_COMMIT}
            TZ: ${TZ}
        image: moboweb
        volumes:
            - "./shared/cms/custom:/var/www/cms/custom:Z"
            - "./shared/backup:/var/www/backup:Z"
            - "./shared/cms/web/theme/custom:/var/www/cms/web/theme/custom:Z"
            - "./shared/cms/library:/var/www/cms/library:Z"
            - "./shared/cms/web/userscripts:/var/www/cms/web/userscripts:Z"
            - "./shared/cms/ca-certs:/var/www/cms/ca-certs:Z"
        environment:
            - MYSQL_HOST=mobo-db
            - XMR_HOST=mobo-xmr
            - CMS_USE_MEMCACHED=true
            - MEMCACHED_HOST=mobo-memcached
        env_file: config.env
        restart: always
        ports:
            - "80:80"
        mem_limit: 1g
        container_name: MoboCMS-web
    mobo-memcached:
        image: memcached:alpine
        command: memcached -m 15
        restart: always
        mem_limit: 100M
        container_name: MoboCMS-memcached
    mobo-quickchart:
      image: ianw/quickchart
      restart: always
      container_name: MoboCMS-quickchart
